# -*- coding: utf-8 -*-
"""cosine_function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZhMW8nJxzBCKWqfywSdzO4b43UA49iB
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-2 * np.pi, 2 * np.pi, 100)


y = np.cos(x)


plt.figure(figsize=(10, 5))
plt.plot(x, y, label='cos(x)', color='blue', linewidth=2)


plt.title('Cosine Function Plot')
plt.xlabel('x (radians)')
plt.ylabel('cos(x)')
plt.grid(True)
plt.legend()


plt.show()

